import type { TrashItem } from './types';

export const allTrashItems: TrashItem[] = [
	{ name: 'Trasig bärbar dator', targetId: 'elektronikavfall', icon: '💻', category: 'Elektronikavfall' },
	{ name: 'Trasig mobiltelefon', targetId: 'elektronikavfall', icon: '📱', category: 'Elektronikavfall' },
	{ name: 'Trasig stationär dator', targetId: 'elektronikavfall', icon: '🖥️', category: 'Elektronikavfall' },
	{ name: 'Trasigt tangentbord', targetId: 'elektronikavfall', icon: '⌨️', category: 'Elektronikavfall' },
	{ name: 'Trasig datormus', targetId: 'elektronikavfall', icon: '🖱️', category: 'Elektronikavfall' },
	{ name: 'Trasig skrivare', targetId: 'elektronikavfall', icon: '🖨️', category: 'Elektronikavfall' },
	{ name: 'Trasig TV', targetId: 'elektronikavfall', icon: '📺', category: 'Elektronikavfall' },
	{ name: 'Trasig radio', targetId: 'elektronikavfall', icon: '📻', category: 'Elektronikavfall' },
	{ name: 'Trasig handkontroll', targetId: 'elektronikavfall', icon: '🎮', category: 'Elektronikavfall' },
	{ name: 'Trasig ficklampa', targetId: 'elektronikavfall', icon: '🔦', category: 'Elektronikavfall' },
	{ name: 'Kasserad sladd', targetId: 'elektronikavfall', icon: '🔌', category: 'Elektronikavfall' },
	{ name: 'Trasig mikrovågsugn', targetId: 'elektronikavfall', icon: '📟', category: 'Elektronikavfall' },

	{ name: 'Fungerande TV', targetId: 'aterbruk', icon: '📺', category: 'Återbruk' },
	{ name: 'Fungerande mobiltelefon', targetId: 'aterbruk', icon: '📱', category: 'Återbruk' },
	{ name: 'Hel tröja', targetId: 'aterbruk', icon: '🧥', category: 'Återbruk' },
	{ name: 'Hel byxa', targetId: 'aterbruk', icon: '👖', category: 'Återbruk' },
	{ name: 'Hela skor', targetId: 'aterbruk', icon: '👞', category: 'Återbruk' },
	{ name: 'Fin klänning', targetId: 'aterbruk', icon: '👗', category: 'Återbruk' },
	{ name: 'Fin vas', targetId: 'aterbruk', icon: '🏺', category: 'Återbruk' },
	{ name: 'Helt gosedjur', targetId: 'aterbruk', icon: '🧸', category: 'Återbruk' },
	{ name: 'Läslig bok', targetId: 'aterbruk', icon: '📚', category: 'Återbruk' },
	{ name: 'Fungerande lampa', targetId: 'aterbruk', icon: '💡', category: 'Återbruk' },
	{ name: 'Fina bestick', targetId: 'aterbruk', icon: '🥄', category: 'Återbruk' },
	{ name: 'Hel ryggsäck', targetId: 'aterbruk', icon: '🎒', category: 'Återbruk' },

	{ name: 'Hela skidor', targetId: 'sport_fritid', icon: '🎿', category: 'Sport & Fritid' },
	{ name: 'Hela skridskor', targetId: 'sport_fritid', icon: '⛸️', category: 'Sport & Fritid' },
	{ name: 'Fungerande cykel', targetId: 'sport_fritid', icon: '🚲', category: 'Sport & Fritid' },
	{ name: 'Användbart tält', targetId: 'sport_fritid', icon: '⛺', category: 'Sport & Fritid' },
	{ name: 'Hel flytväst', targetId: 'sport_fritid', icon: '🦺', category: 'Sport & Fritid' },
	{ name: 'Hel fotboll', targetId: 'sport_fritid', icon: '⚽', category: 'Sport & Fritid' },
	{ name: 'Hel basketboll', targetId: 'sport_fritid', icon: '🏀', category: 'Sport & Fritid' },
	{ name: 'Helt tennisracket', targetId: 'sport_fritid', icon: '🎾', category: 'Sport & Fritid' },
	{ name: 'Hel ishockeyklubba', targetId: 'sport_fritid', icon: '🏒', category: 'Sport & Fritid' },
	{ name: 'Helt fiskespö', targetId: 'sport_fritid', icon: '🎣', category: 'Sport & Fritid' },
	{ name: 'Hel cykelhjälm', targetId: 'sport_fritid', icon: '⛑️', category: 'Sport & Fritid' },
	{ name: 'Hel badmintonboll', targetId: 'sport_fritid', icon: '🏸', category: 'Sport & Fritid' },
	{ name: 'Hel drake', targetId: 'sport_fritid', icon: '🪁', category: 'Sport & Fritid' },

	{ name: 'Trasig tröja', targetId: 'energiatervinning', icon: '🧥', category: 'Energiåtervinning' },
	{ name: 'Trasig byxa', targetId: 'energiatervinning', icon: '👖', category: 'Energiåtervinning' },
	{ name: 'Utslitna strumpor', targetId: 'energiatervinning', icon: '🧦', category: 'Energiåtervinning' },
	{ name: 'Trasiga skor', targetId: 'energiatervinning', icon: '👞', category: 'Energiåtervinning' },
	{ name: 'Trasigt gosedjur', targetId: 'energiatervinning', icon: '🧸', category: 'Energiåtervinning' },
	{ name: 'Punkterad fotboll', targetId: 'energiatervinning', icon: '⚽', category: 'Energiåtervinning' },
	{ name: 'Trasigt paraply', targetId: 'energiatervinning', icon: '☂️', category: 'Energiåtervinning' },
	{ name: 'Trasig ryggsäck', targetId: 'energiatervinning', icon: '🎒', category: 'Energiåtervinning' },
	{ name: 'Trasig plastleksak', targetId: 'energiatervinning', icon: '🪀', category: 'Energiåtervinning' },
	{ name: 'Trasig tvättsvamp', targetId: 'energiatervinning', icon: '🧽', category: 'Energiåtervinning' },

	{ name: 'Trasig cykel', targetId: 'metall', icon: '🚲', category: 'Metall' },
	{ name: 'Rostig stekpanna', targetId: 'metall', icon: '🍳', category: 'Metall' },
	{ name: 'Skev kastrull', targetId: 'metall', icon: '🍲', category: 'Metall' },
	{ name: 'Rostig sax', targetId: 'metall', icon: '✂️', category: 'Metall' },
	{ name: 'Trasig hammare', targetId: 'metall', icon: '🔨', category: 'Metall' },
	{ name: 'Rostig skruv', targetId: 'metall', icon: '🔩', category: 'Metall' },
	{ name: 'Trasigt kugghjul', targetId: 'metall', icon: '⚙️', category: 'Metall' },
	{ name: 'Rostig skiftnyckel', targetId: 'metall', icon: '🔧', category: 'Metall' },
	{ name: 'Trasig yxa', targetId: 'metall', icon: '🪓', category: 'Metall' },
	{ name: 'Trasig kundvagn', targetId: 'metall', icon: '🛒', category: 'Metall' },

	{ name: 'Urladdat batteri', targetId: 'farligt_avfall', icon: '🔋', category: 'Farligt Avfall' },
	{ name: 'Trasig glödlampa', targetId: 'farligt_avfall', icon: '💡', category: 'Farligt Avfall' },
	{ name: 'Gammalt oljefat', targetId: 'farligt_avfall', icon: '🛢️', category: 'Farligt Avfall' },
	{ name: 'Tom bensindunk', targetId: 'farligt_avfall', icon: '⛽', category: 'Farligt Avfall' },
	{ name: 'Gammal kemikalie', targetId: 'farligt_avfall', icon: '🧪', category: 'Farligt Avfall' },
	{ name: 'Intorkad målarfärg', targetId: 'farligt_avfall', icon: '🎨', category: 'Farligt Avfall' },
	{ name: 'Gammalt nagellack', targetId: 'farligt_avfall', icon: '💅', category: 'Farligt Avfall' },

	{ name: 'Tom kartonglåda', targetId: 'pappersforpackningar', icon: '📦', category: 'Pappersförpackningar' },
	{ name: 'Tom pappersrulle', targetId: 'pappersforpackningar', icon: '🧻', category: 'Pappersförpackningar' },
	{ name: 'Tom papperskasse', targetId: 'pappersforpackningar', icon: '🛍️', category: 'Pappersförpackningar' },
	{ name: 'Tomt mjölkpaket', targetId: 'pappersforpackningar', icon: '🥛', category: 'Pappersförpackningar' },
	{ name: 'Tom pizzakartong', targetId: 'pappersforpackningar', icon: '🍕', category: 'Pappersförpackningar' },
	{ name: 'Tom äggkartong', targetId: 'pappersforpackningar', icon: '🥚', category: 'Pappersförpackningar' },
	{ name: 'Utdaterad dagstidning', targetId: 'returpapper', icon: '📰', category: 'Returpapper' },

	{ name: 'Tom plastflaska', targetId: 'plastforpackningar', icon: '🍼', category: 'Plastförpackningar' },
	{ name: 'Tom plastburk', targetId: 'plastforpackningar', icon: '🫙', category: 'Plastförpackningar' },
	{ name: 'Tom plasthink', targetId: 'plastforpackningar', icon: '🪣', category: 'Plastförpackningar' },
	{ name: 'Tom schampoflaska', targetId: 'plastforpackningar', icon: '🧴', category: 'Plastförpackningar' },
	{ name: 'Kasserat godispapper', targetId: 'plastforpackningar', icon: '🍬', category: 'Plastförpackningar' },
	{ name: 'Använd plastmugg', targetId: 'plastforpackningar', icon: '🥤', category: 'Plastförpackningar' },

	{ name: 'Tom konservburk', targetId: 'metallforpackningar', icon: '🥫', category: 'Metallförpackningar' },
	{ name: 'Använd aluminiumfolie', targetId: 'metallforpackningar', icon: '🌯', category: 'Metallförpackningar' },
	{ name: 'Böjd kapsyl', targetId: 'metallforpackningar', icon: '🍾', category: 'Metallförpackningar' },

	{ name: 'Trasig toalettstol', targetId: 'porslin_keramik', icon: '🚽', category: 'Porslin & Keramik' },
	{ name: 'Sprucken tallrik', targetId: 'porslin_keramik', icon: '🍽️', category: 'Porslin & Keramik' },
	{ name: 'Trasig kaffekopp', targetId: 'porslin_keramik', icon: '☕', category: 'Porslin & Keramik' },
	{ name: 'Trasig lerkruka', targetId: 'porslin_keramik', icon: '🏺', category: 'Porslin & Keramik' },
	{ name: 'Sprucken kakelplatta', targetId: 'porslin_keramik', icon: '⬜', category: 'Porslin & Keramik' },

	{ name: 'Trasig trästol', targetId: 'tra', icon: '🪑', category: 'Trä' },
	{ name: 'Trasig byrå', targetId: 'tra', icon: '🗄️', category: 'Trä' },
	{ name: 'Trasig trädörr', targetId: 'tra', icon: '🚪', category: 'Trä' },
	{ name: 'Avbruten trästege', targetId: 'tra', icon: '🪜', category: 'Trä' },

	{ name: 'Ruttet äpple', targetId: 'matavfall', icon: '🍎', category: 'Matavfall' },
	{ name: 'Bananskal', targetId: 'matavfall', icon: '🍌', category: 'Matavfall' },
	{ name: 'Morotsskal', targetId: 'matavfall', icon: '🥕', category: 'Matavfall' },
	{ name: 'Mögligt bröd', targetId: 'matavfall', icon: '🍞', category: 'Matavfall' },
	{ name: 'Gammal ostkant', targetId: 'matavfall', icon: '🧀', category: 'Matavfall' },
	{ name: 'Köttben', targetId: 'matavfall', icon: '🦴', category: 'Matavfall' },
	{ name: 'Kasserad croissant', targetId: 'matavfall', icon: '🥐', category: 'Matavfall' },
	{ name: 'Rutten vattenmelon', targetId: 'matavfall', icon: '🍉', category: 'Matavfall' },

	{ name: 'Trasig soffa', targetId: 'stoppade_mobler', icon: '🛋️', category: 'Stoppade Möbler' },
	{ name: 'Trasig säng', targetId: 'stoppade_mobler', icon: '🛏️', category: 'Stoppade Möbler' },
	{ name: 'Söndrig fåtölj', targetId: 'stoppade_mobler', icon: '💺', category: 'Stoppade Möbler' },

	{ name: 'Avbruten kvist', targetId: 'ris_grenar', icon: '🎋', category: 'Ris & Grenar' },
	{ name: 'Ruttet vedträ', targetId: 'ris_grenar', icon: '🪵', category: 'Ris & Grenar' },
	{ name: 'Torkad julgran', targetId: 'ris_grenar', icon: '🎄', category: 'Ris & Grenar' },
	{ name: 'Högt gräs', targetId: 'gras_lov', icon: '🌱', category: 'Gräs & Löv' },
	{ name: 'Torra löv', targetId: 'gras_lov', icon: '🍂', category: 'Gräs & Löv' },
	{ name: 'Vissen blomma', targetId: 'gras_lov', icon: '🥀', category: 'Gräs & Löv' },

	{ name: 'Sprucken tegelsten', targetId: 'sten_grus', icon: '🧱', category: 'Sten & Grus' },
	{ name: 'Gråsten', targetId: 'sten_grus', icon: '🪨', category: 'Sten & Grus' },

	{ name: 'Trasig pulka', targetId: 'hardplast', icon: '🛷', category: 'Hårdplast' },

	{ name: 'Rostig fiskekrok', targetId: 'fiskeredskap', icon: '🪝', category: 'Fiskeredskap' },
	{ name: 'Trasigt fiskenät', targetId: 'fiskeredskap', icon: '🕸️', category: 'Fiskeredskap' },

	{ name: 'Gammalt smör', targetId: 'matfett', icon: '🧈', category: 'Matfett' },
	{ name: 'Gammal olivolja', targetId: 'matfett', icon: '🫒', category: 'Matfett' },

	{ name: 'Trasig spegel', targetId: 'planglas', icon: '🪞', category: 'Planglas' },
	{ name: 'Trasigt fönster', targetId: 'planglas', icon: '🪟', category: 'Planglas' },

	{ name: 'Krossat dricksglas', targetId: 'ej_atervinningsbart', icon: '🥃', category: 'Ej Återvinningsbart' },
	{ name: 'Använd blöja', targetId: 'ej_atervinningsbart', icon: '👶', category: 'Ej Återvinningsbart' },

	{ name: 'Ruttet tågräls (Slipers)', targetId: 'impregnerat_tra', icon: '🛤️', category: 'Impregnerat Trä' },
	{ name: 'Utryckt trädstubbe', targetId: 'stubbar_rotter', icon: '🪵', category: 'Stubbar & Rötter' },
	{ name: 'Uppbruten asfalt', targetId: 'asfalt', icon: '🛣️', category: 'Asfalt' },

	{ name: 'Trasig kyl', targetId: 'kyl_frys', icon: '🥶', category: 'Kyl & Frys' },
	{ name: 'Trasig spis', targetId: 'vitvaror', icon: '🍳', category: 'Vitvaror' }
];