import * as Icons from '$lib/icons';

export const allTrashItems = [
	{ name: 'Kylskåp', target: Icons.KylFrys, icon: '🧊', category: 'Kyl & Frys' },
	{ name: 'Frysskåp', target: Icons.KylFrys, icon: '❄️', category: 'Kyl & Frys' },
	{ name: 'Frysbox', target: Icons.KylFrys, icon: '❄️', category: 'Kyl & Frys' },
	{ name: 'Varmvattenberedare', target: Icons.KylFrys, icon: '🚰', category: 'Kyl & Frys' },

	{ name: 'Dator', target: Icons.Elektronikavfall, icon: '💻', category: 'Elektronikavfall' },
	{ name: 'Telefon', target: Icons.Elektronikavfall, icon: '📱', category: 'Elektronikavfall' },
	{ name: 'Smarttelefon', target: Icons.Elektronikavfall, icon: '📱', category: 'Elektronikavfall' },
	{ name: 'Dammsugare', target: Icons.Elektronikavfall, icon: '🧹', category: 'Elektronikavfall' },
	{ name: 'Mikrovågsugn', target: Icons.Elektronikavfall, icon: '🍿', category: 'Elektronikavfall' },
	{ name: 'Elhandverktyg', target: Icons.Elektronikavfall, icon: '🪛', category: 'Elektronikavfall' },
	{ name: 'Armaturer', target: Icons.Elektronikavfall, icon: '💡', category: 'Elektronikavfall' },
	{ name: 'Kabel', target: Icons.Elektronikavfall, icon: '🔌', category: 'Elektronikavfall' },
	{ name: 'Brödrost', target: Icons.Elektronikavfall, icon: '🍞', category: 'Elektronikavfall' },

	{ name: 'Spillolja', target: Icons.FarligtAvfall, icon: '🛢️', category: 'Farligt Avfall' },
	{ name: 'Diesel', target: Icons.FarligtAvfall, icon: '⛽', category: 'Farligt Avfall' },
	{ name: 'Färgrester', target: Icons.FarligtAvfall, icon: '🎨', category: 'Farligt Avfall' },
	{ name: 'Målarfärg', target: Icons.FarligtAvfall, icon: '🎨', category: 'Farligt Avfall' },
	{ name: 'Kemikalier', target: Icons.FarligtAvfall, icon: '🧪', category: 'Farligt Avfall' },
	{ name: 'Lysrör', target: Icons.FarligtAvfall, icon: '💡', category: 'Farligt Avfall' },
	{ name: 'Bilbatterier', target: Icons.FarligtAvfall, icon: '🔋', category: 'Farligt Avfall' },
	{ name: 'TV', target: Icons.FarligtAvfall, icon: '📺', category: 'Farligt Avfall' },
	{ name: 'Bildskärm', target: Icons.FarligtAvfall, icon: '🖥️', category: 'Farligt Avfall' },
	{ name: 'Värmepump', target: Icons.FarligtAvfall, icon: '♨️', category: 'Farligt Avfall' },
	{ name: 'Nagellack', target: Icons.FarligtAvfall, icon: '💅', category: 'Farligt Avfall' },

	{ name: 'Brädor', target: Icons.Tra, icon: '🪵', category: 'Trä' },
	{ name: 'Plank', target: Icons.Tra, icon: '🪵', category: 'Trä' },
	{ name: 'Spånskivor', target: Icons.Tra, icon: '🪵', category: 'Trä' },
	{ name: 'Plywood', target: Icons.Tra, icon: '🪵', category: 'Trä' },
	{ name: 'Masonit', target: Icons.Tra, icon: '🪵', category: 'Trä' },
	{ name: 'Trädörrar (utan glas)', target: Icons.Tra, icon: '🚪', category: 'Trä' },
	{ name: 'Trämöbler', target: Icons.Tra, icon: '🪑', category: 'Trä' },
	{ name: 'Trasig byrå', target: Icons.Tra, icon: '🪑', category: 'Trä' },
	{ name: 'Avbruten bräda', target: Icons.Tra, icon: '🪵', category: 'Trä' },

	{ name: 'Wellpapp', target: Icons.Pappersforpackningar, icon: '📦', category: 'Pappersförpackningar' },
	{ name: 'Papprör', target: Icons.Pappersforpackningar, icon: '🧻', category: 'Pappersförpackningar' },
	{ name: 'Kartonger', target: Icons.Pappersforpackningar, icon: '📦', category: 'Pappersförpackningar' },
	{ name: 'Flyttlådor', target: Icons.Pappersforpackningar, icon: '📦', category: 'Pappersförpackningar' },
	{ name: 'Matförpackningar (papper)', target: Icons.Pappersforpackningar, icon: '🥡', category: 'Pappersförpackningar' },
	{ name: 'Äggkartonger', target: Icons.Pappersforpackningar, icon: '🥚', category: 'Pappersförpackningar' },
	{ name: 'Papperspåsar', target: Icons.Pappersforpackningar, icon: '🛍️', category: 'Pappersförpackningar' },
	{ name: 'Papperskassar', target: Icons.Pappersforpackningar, icon: '🛍️', category: 'Pappersförpackningar' },
	{ name: 'Mjölkpaket', target: Icons.Pappersforpackningar, icon: '🥛', category: 'Pappersförpackningar' },
	{ name: 'Pizzakartong', target: Icons.Pappersforpackningar, icon: '🍕', category: 'Pappersförpackningar' },

	{ name: 'Mjuka plastförpackningar', target: Icons.Plastforpackningar, icon: '🍬', category: 'Plastförpackningar' },
	{ name: 'Hårda plastförpackningar', target: Icons.Plastforpackningar, icon: '🧴', category: 'Plastförpackningar' },
	{ name: 'Plastflaskor', target: Icons.Plastforpackningar, icon: '🧴', category: 'Plastförpackningar' },
	{ name: 'Plastburkar', target: Icons.Plastforpackningar, icon: '🫙', category: 'Plastförpackningar' },
	{ name: 'Plasthinkar', target: Icons.Plastforpackningar, icon: '🪣', category: 'Plastförpackningar' },
	{ name: 'Plastdunkar', target: Icons.Plastforpackningar, icon: '🛢️', category: 'Plastförpackningar' },
	{ name: 'Plastpåsar', target: Icons.Plastforpackningar, icon: '🛍️', category: 'Plastförpackningar' },
	{ name: 'Plastkassar', target: Icons.Plastforpackningar, icon: '🛍️', category: 'Plastförpackningar' },
	{ name: 'Frigolit (förpackning)', target: Icons.Plastforpackningar, icon: '🧊', category: 'Plastförpackningar' },
	{ name: 'Schampoflaska', target: Icons.Plastforpackningar, icon: '🧴', category: 'Plastförpackningar' },

	{ name: 'Metallock', target: Icons.Metallforpackningar, icon: '🥫', category: 'Metallförpackningar' },
	{ name: 'Kapsyler', target: Icons.Metallforpackningar, icon: '🍾', category: 'Metallförpackningar' },
	{ name: 'Aluminiumfolie', target: Icons.Metallforpackningar, icon: '🌯', category: 'Metallförpackningar' },
	{ name: 'Konservburkar', target: Icons.Metallforpackningar, icon: '🥫', category: 'Metallförpackningar' },

	{ name: 'WC-stolar', target: Icons.PorslinKeramik, icon: '🚽', category: 'Porslin & Keramik' },
	{ name: 'Toalettstol', target: Icons.PorslinKeramik, icon: '🚽', category: 'Porslin & Keramik' },
	{ name: 'Handfat', target: Icons.PorslinKeramik, icon: '🚰', category: 'Porslin & Keramik' },
	{ name: 'Klinker', target: Icons.PorslinKeramik, icon: '🧱', category: 'Porslin & Keramik' },
	{ name: 'Kakel', target: Icons.PorslinKeramik, icon: '🧱', category: 'Porslin & Keramik' },
	{ name: 'Keramik', target: Icons.PorslinKeramik, icon: '🏺', category: 'Porslin & Keramik' },
	{ name: 'Lerkrukor', target: Icons.PorslinKeramik, icon: '🪴', category: 'Porslin & Keramik' },
	{ name: 'Kaffekopp', target: Icons.PorslinKeramik, icon: '☕', category: 'Porslin & Keramik' },
	{ name: 'Trasig tallrik', target: Icons.PorslinKeramik, icon: '🍽️', category: 'Porslin & Keramik' },

	{ name: 'Dörrar med isolering', target: Icons.StoppadeMobler, icon: '🚪', category: 'Stoppade Möbler' },
	{ name: 'Laminatgolv', target: Icons.StoppadeMobler, icon: '🪵', category: 'Stoppade Möbler' },
	{ name: 'Tavlor', target: Icons.StoppadeMobler, icon: '🖼️', category: 'Stoppade Möbler' },
	{ name: 'Presenningar', target: Icons.StoppadeMobler, icon: '⛺', category: 'Stoppade Möbler' },
	{ name: 'Plastslangar', target: Icons.StoppadeMobler, icon: '🪢', category: 'Stoppade Möbler' },
	{ name: 'Trasig soffa', target: Icons.StoppadeMobler, icon: '🛋️', category: 'Stoppade Möbler' },
	{ name: 'Gammal fåtölj', target: Icons.StoppadeMobler, icon: '💺', category: 'Stoppade Möbler' },

	{ name: 'Skumgummimadrasser', target: Icons.Energiatervinning, icon: '🛏️', category: 'Energiåtervinning' },
	{ name: 'Möbeldynor', target: Icons.Energiatervinning, icon: '🛋️', category: 'Energiåtervinning' },
	{ name: 'Mattor', target: Icons.Energiatervinning, icon: '🪘', category: 'Energiåtervinning' },
	{ name: 'Större frigolit', target: Icons.Energiatervinning, icon: '🧊', category: 'Energiåtervinning' },
	{ name: 'Lupiner', target: Icons.Energiatervinning, icon: '🌿', category: 'Energiåtervinning' },
	{ name: 'Invasiva växter', target: Icons.Energiatervinning, icon: '🌿', category: 'Energiåtervinning' },
	{ name: 'Trasiga byxor', target: Icons.Energiatervinning, icon: '👖', category: 'Energiåtervinning' },

	{ name: 'Värmeljuskoppar', target: Icons.Metall, icon: '🕯️', category: 'Metall' },
	{ name: 'Järnskrot', target: Icons.Metall, icon: '⚙️', category: 'Metall' },
	{ name: 'Gräsklippare', target: Icons.Metall, icon: '🚜', category: 'Metall' },
	{ name: 'Cyklar', target: Icons.Metall, icon: '🚲', category: 'Metall' },
	{ name: 'Sparkar', target: Icons.Metall, icon: '🛷', category: 'Metall' },
	{ name: 'Badkar', target: Icons.Metall, icon: '🛁', category: 'Metall' },
	{ name: 'Metallstolar', target: Icons.Metall, icon: '🪑', category: 'Metall' },
	{ name: 'Kastruller', target: Icons.Metall, icon: '🍲', category: 'Metall' },
	{ name: 'Cykelram', target: Icons.Metall, icon: '🚲', category: 'Metall' },
	{ name: 'Stekpanna', target: Icons.Metall, icon: '🍳', category: 'Metall' },

	{ name: 'Mineralull', target: Icons.EjAtervinningsbart, icon: '☁️', category: 'Ej Återvinningsbart' },
	{ name: 'Glasull', target: Icons.EjAtervinningsbart, icon: '☁️', category: 'Ej Återvinningsbart' },
	{ name: 'Stenull', target: Icons.EjAtervinningsbart, icon: '☁️', category: 'Ej Återvinningsbart' },
	{ name: 'Dricksglas', target: Icons.EjAtervinningsbart, icon: '🥛', category: 'Ej Återvinningsbart' },
	{ name: 'Glasskålar', target: Icons.EjAtervinningsbart, icon: '🥣', category: 'Ej Återvinningsbart' },
	{ name: 'Prydnadsföremål (glas)', target: Icons.EjAtervinningsbart, icon: '🔮', category: 'Ej Återvinningsbart' },
	{ name: 'Sågspån (förpackat)', target: Icons.EjAtervinningsbart, icon: '🪵', category: 'Ej Återvinningsbart' },
	{ name: 'Dammsugarpåse', target: Icons.EjAtervinningsbart, icon: '🧹', category: 'Ej Återvinningsbart' },
	{ name: 'Blöja', target: Icons.EjAtervinningsbart, icon: '👶', category: 'Ej Återvinningsbart' },

	{ name: 'Hela/rena kläder', target: Icons.Textilinsamling, icon: '👕', category: 'Textilinsamling' },
	{ name: 'Hel/ren hemtextil', target: Icons.Textilinsamling, icon: '🛏️', category: 'Textilinsamling' },
	{ name: 'Hela/rena skor', target: Icons.Textilinsamling, icon: '👞', category: 'Textilinsamling' },

	{ name: 'Gräs', target: Icons.GrasLov, icon: '🌱', category: 'Gräs & Löv' },
	{ name: 'Löv', target: Icons.GrasLov, icon: '🍂', category: 'Gräs & Löv' },
	{ name: 'Kottar', target: Icons.GrasLov, icon: '🌲', category: 'Gräs & Löv' },
	{ name: 'Barr', target: Icons.GrasLov, icon: '🌲', category: 'Gräs & Löv' },
	{ name: 'Växter', target: Icons.GrasLov, icon: '🪴', category: 'Gräs & Löv' },
	{ name: 'Fallfrukt', target: Icons.GrasLov, icon: '🍎', category: 'Gräs & Löv' },
	{ name: 'Jord', target: Icons.GrasLov, icon: '🪨', category: 'Gräs & Löv' },
	{ name: 'Gräsklipp', target: Icons.GrasLov, icon: '🌿', category: 'Gräs & Löv' },
	{ name: 'Höstlöv', target: Icons.GrasLov, icon: '🍂', category: 'Gräs & Löv' },

	{ name: 'Kvistar', target: Icons.RisGrenar, icon: '🌲', category: 'Ris & Grenar' },
	{ name: 'Sly', target: Icons.RisGrenar, icon: '🌿', category: 'Ris & Grenar' },
	{ name: 'Häck-klipp', target: Icons.RisGrenar, icon: '✂️', category: 'Ris & Grenar' },
	{ name: 'Vedträ', target: Icons.RisGrenar, icon: '🪵', category: 'Ris & Grenar' },
	{ name: 'Stockar', target: Icons.RisGrenar, icon: '🪵', category: 'Ris & Grenar' },
	{ name: 'Huggkubbar', target: Icons.RisGrenar, icon: '🪵', category: 'Ris & Grenar' },

	{ name: 'Betongplintar', target: Icons.StenGrus, icon: '🪨', category: 'Sten & Grus' },
	{ name: 'Marksten', target: Icons.StenGrus, icon: '🧱', category: 'Sten & Grus' },
	{ name: 'Trädgårdsplattor', target: Icons.StenGrus, icon: '🪨', category: 'Sten & Grus' },
	{ name: 'Tegelstenar', target: Icons.StenGrus, icon: '🧱', category: 'Sten & Grus' },
	{ name: 'Tegelpannor', target: Icons.StenGrus, icon: '🏠', category: 'Sten & Grus' },
	{ name: 'Gatsten', target: Icons.StenGrus, icon: '🪨', category: 'Sten & Grus' },

	{ name: 'Spisar', target: Icons.Vitvaror, icon: '♨️', category: 'Vitvaror' },
	{ name: 'Diskmaskiner', target: Icons.Vitvaror, icon: '🍽️', category: 'Vitvaror' },
	{ name: 'Köksfläktar', target: Icons.Vitvaror, icon: '💨', category: 'Vitvaror' },
	{ name: 'Tvättmaskiner', target: Icons.Vitvaror, icon: '🧺', category: 'Vitvaror' },
	{ name: 'Torktumlare', target: Icons.Vitvaror, icon: '🌀', category: 'Vitvaror' },
	{ name: 'Torkskåp', target: Icons.Vitvaror, icon: '🚪', category: 'Vitvaror' },

	{ name: 'Pulkor', target: Icons.Hardplast, icon: '🛷', category: 'Hårdplast' },
	{ name: 'Utemöbler (plast)', target: Icons.Hardplast, icon: '🪑', category: 'Hårdplast' },
	{ name: 'Stora plastföremål', target: Icons.Hardplast, icon: '🪣', category: 'Hårdplast' },
	{ name: 'Plaststol', target: Icons.Hardplast, icon: '🪑', category: 'Hårdplast' },

	{ name: 'Skidor', target: Icons.SportFritid, icon: '🎿', category: 'Sport & Fritid' },
	{ name: 'Skridskor', target: Icons.SportFritid, icon: '⛸️', category: 'Sport & Fritid' },
	{ name: 'Inlines', target: Icons.SportFritid, icon: '🛼', category: 'Sport & Fritid' },
	{ name: 'Flytvästar', target: Icons.SportFritid, icon: '🦺', category: 'Sport & Fritid' },
	{ name: 'Tält', target: Icons.SportFritid, icon: '⛺', category: 'Sport & Fritid' },
	{ name: 'Bollar', target: Icons.SportFritid, icon: '⚽', category: 'Sport & Fritid' },
	{ name: 'Klubbor', target: Icons.SportFritid, icon: '🏒', category: 'Sport & Fritid' },
	{ name: 'Fiskespön', target: Icons.SportFritid, icon: '🎣', category: 'Sport & Fritid' },
	{ name: 'Fotbollsskor', target: Icons.SportFritid, icon: '👟', category: 'Sport & Fritid' },
	{ name: 'Hjälmar', target: Icons.SportFritid, icon: '⛑️', category: 'Sport & Fritid' },
	{ name: 'Stormkök', target: Icons.SportFritid, icon: '🍳', category: 'Sport & Fritid' },
	{ name: 'Fotboll', target: Icons.SportFritid, icon: '⚽', category: 'Sport & Fritid' },

	{ name: 'Tryckimpregnerat trä', target: Icons.ImpragneratTra, icon: '🪵', category: 'Impregnerat Trä' },
	{ name: 'Slipers', target: Icons.ImpragneratTra, icon: '🛤️', category: 'Impregnerat Trä' },

	{ name: 'Fiskespö (plast)', target: Icons.Fiskeredskap, icon: '🎣', category: 'Fiskeredskap' },
	{ name: 'Fiskedrag', target: Icons.Fiskeredskap, icon: '🪝', category: 'Fiskeredskap' },
	{ name: 'Nät', target: Icons.Fiskeredskap, icon: '🕸️', category: 'Fiskeredskap' },
	{ name: 'Trasigt fiskenät', target: Icons.Fiskeredskap, icon: '🎣', category: 'Fiskeredskap' },

	{ name: 'Matfett', target: Icons.Matfett, icon: '🧈', category: 'Matfett' },
	{ name: 'Matolja', target: Icons.Matfett, icon: '🛢️', category: 'Matfett' },
	{ name: 'Frityrolja', target: Icons.Matfett, icon: '🛢️', category: 'Matfett' },
	{ name: 'Olja från inlagda livsmedel', target: Icons.Matfett, icon: '🫙', category: 'Matfett' },

	{ name: 'Helpallar', target: Icons.Pallinsamling, icon: '🪚', category: 'Pallinsamling' },
	{ name: 'Halvpallar', target: Icons.Pallinsamling, icon: '🪚', category: 'Pallinsamling' },
	{ name: 'Byggpall', target: Icons.Pallinsamling, icon: '🪚', category: 'Pallinsamling' },
	{ name: 'SJ-pall', target: Icons.Pallinsamling, icon: '🪚', category: 'Pallinsamling' },
	{ name: 'EUR-pall', target: Icons.Pallinsamling, icon: '🪚', category: 'Pallinsamling' },
	{ name: 'Engångspall', target: Icons.Pallinsamling, icon: '🪚', category: 'Pallinsamling' },
	{ name: 'Pallkragar', target: Icons.Pallinsamling, icon: '🪚', category: 'Pallinsamling' },
	{ name: 'Lastpall', target: Icons.Pallinsamling, icon: '🪚', category: 'Pallinsamling' },

	{ name: 'Möbler (hela)', target: Icons.Aterbruk, icon: '🛋️', category: 'Återbruk' },
	{ name: 'Heminredning', target: Icons.Aterbruk, icon: '🖼️', category: 'Återbruk' },
	{ name: 'Husgeråd', target: Icons.Aterbruk, icon: '🍽️', category: 'Återbruk' },
	{ name: 'Cyklar (återbruk)', target: Icons.Aterbruk, icon: '🚲', category: 'Återbruk' },
	{ name: 'Användbara kläder', target: Icons.Aterbruk, icon: '👗', category: 'Återbruk' },
	{ name: 'Fina leksaker', target: Icons.Aterbruk, icon: '🧸', category: 'Återbruk' },

	{ name: 'Ofärgade glasflaskor', target: Icons.OfargatGlas, icon: '🍾', category: 'Ofärgat Glas' },
	{ name: 'Ofärgade glasburkar', target: Icons.OfargatGlas, icon: '🫙', category: 'Ofärgat Glas' },

	{ name: 'Färgade glasflaskor', target: Icons.FargatGlas, icon: '🍾', category: 'Färgat Glas' },
	{ name: 'Färgade glasburkar', target: Icons.FargatGlas, icon: '🫙', category: 'Färgat Glas' },

	{ name: 'Balkongdörr med karm', target: Icons.Planglas, icon: '🚪', category: 'Planglas' },
	{ name: 'Fönster med karm', target: Icons.Planglas, icon: '🪟', category: 'Planglas' },
	{ name: 'Fönsterglas', target: Icons.Planglas, icon: '🪟', category: 'Planglas' },
	{ name: 'Spegelglas', target: Icons.Planglas, icon: '🪞', category: 'Planglas' },
	{ name: 'Glasskivor', target: Icons.Planglas, icon: '🪟', category: 'Planglas' },
	{ name: 'Trasigt fönster', target: Icons.Planglas, icon: '🪟', category: 'Planglas' },

	{ name: 'Stubbar', target: Icons.StubbarRotter, icon: '🪵', category: 'Stubbar & Rötter' },
	{ name: 'Rötter', target: Icons.StubbarRotter, icon: '🪢', category: 'Stubbar & Rötter' },

	{ name: 'Gipsskivor', target: Icons.Gips, icon: '🧱', category: 'Gips' },
	{ name: 'Gipsbruk', target: Icons.Gips, icon: '🏺', category: 'Gips' },
	{ name: 'Gipspulver', target: Icons.Gips, icon: '💨', category: 'Gips' },

	{ name: 'Pantburkar', target: Icons.Storpantarmasking, icon: '🥫', category: 'Storpantarmaskin' },
	{ name: 'PET-flaskor (pant)', target: Icons.Storpantarmasking, icon: '🍾', category: 'Storpantarmaskin' },

	{ name: 'Asfalt', target: Icons.Asfalt, icon: '🛣️', category: 'Asfalt' }
];