import * as Icons from '$lib/icons';

export const allTrashItems = [
	{ name: 'Kylskåp', target: Icons.KylFrys, icon: '🧊', category: 'Kyl & Frys' },
	{ name: 'Frysbox', target: Icons.KylFrys, icon: '❄️', category: 'Kyl & Frys' },
	{ name: 'Gammal TV', target: Icons.Elektronikavfall, icon: '📺', category: 'Elektronikavfall' },
	{ name: 'Smarttelefon', target: Icons.Elektronikavfall, icon: '📱', category: 'Elektronikavfall' },
	{ name: 'Brödrost', target: Icons.Elektronikavfall, icon: '🍞', category: 'Elektronikavfall' },
	{ name: 'Glasflaska', target: Icons.OfargatGlas, icon: '🍾', category: 'Ofärgat Glas' },
	{ name: 'Syltburk (glas)', target: Icons.OfargatGlas, icon: '🫙', category: 'Ofärgat Glas' },
	{ name: 'Trasig byrå', target: Icons.Tra, icon: '🪑', category: 'Trä' },
	{ name: 'Avbruten bräda', target: Icons.Tra, icon: '🪵', category: 'Trä' },
	{ name: 'Mjölkpaket', target: Icons.Pappersforpackningar, icon: '🥛', category: 'Pappersförpackningar' },
	{ name: 'Papperskasse', target: Icons.Pappersforpackningar, icon: '🛍️', category: 'Pappersförpackningar' },
	{ name: 'Pizzakartong', target: Icons.Pappersforpackningar, icon: '🍕', category: 'Pappersförpackningar' },
	{ name: 'Konservburk', target: Icons.Metallforpackningar, icon: '🥫', category: 'Metallförpackningar' },
	{ name: 'Kapsyl', target: Icons.Metallforpackningar, icon: '🍾', category: 'Metallförpackningar' },
	{ name: 'Plastkasse', target: Icons.Plastforpackningar, icon: '🛍️', category: 'Plastförpackningar' },
	{ name: 'Schampoflaska', target: Icons.Plastforpackningar, icon: '🧴', category: 'Plastförpackningar' },
	{ name: 'Målarfärg', target: Icons.FarligtAvfall, icon: '🎨', category: 'Farligt Avfall' },
	{ name: 'Nagellack', target: Icons.FarligtAvfall, icon: '💅', category: 'Farligt Avfall' },
	{ name: 'Kaffekopp', target: Icons.PorslinKeramik, icon: '☕', category: 'Porslin & Keramik' },
	{ name: 'Trasig tallrik', target: Icons.PorslinKeramik, icon: '🍽️', category: 'Porslin & Keramik' },
	{ name: 'Trasig soffa', target: Icons.StoppadeMobler, icon: '🛋️', category: 'Stoppade Möbler' },
	{ name: 'Gammal fåtölj', target: Icons.StoppadeMobler, icon: '💺', category: 'Stoppade Möbler' },
	{ name: 'Cykelram', target: Icons.Metall, icon: '🚲', category: 'Metall' },
	{ name: 'Stekpanna', target: Icons.Metall, icon: '🍳', category: 'Metall' },
	{ name: 'Dammsugarpåse', target: Icons.EjAtervinningsbart, icon: '🧹', category: 'Ej Återvinningsbart' },
	{ name: 'Blöja', target: Icons.EjAtervinningsbart, icon: '👶', category: 'Ej Återvinningsbart' },
	{ name: 'Gammal tröja', target: Icons.Textilinsamling, icon: '👕', category: 'Textilinsamling' },
	{ name: 'Trasiga byxor', target: Icons.Textilinsamling, icon: '👖', category: 'Textilinsamling' },
	{ name: 'Gräsklipp', target: Icons.GrasLov, icon: '🌿', category: 'Gräs & Löv' },
	{ name: 'Höstlöv', target: Icons.GrasLov, icon: '🍂', category: 'Gräs & Löv' },
	{ name: 'Kvistar', target: Icons.RisGrenar, icon: '🌲', category: 'Ris & Grenar' },
	{ name: 'Gatsten', target: Icons.StenGrus, icon: '🪨', category: 'Sten & Grus' },
	{ name: 'Toalettstol', target: Icons.Wc, icon: '🚽', category: 'WC' },
	{ name: 'Trasigt fönster', target: Icons.Planglas, icon: '🪟', category: 'Planglas' },
	{ name: 'Spis', target: Icons.Vitvaror, icon: '♨️', category: 'Vitvaror' },
	{ name: 'Tvättmaskin', target: Icons.Vitvaror, icon: '🧺', category: 'Vitvaror' },
	{ name: 'Plaststol', target: Icons.Hardplast, icon: '🪑', category: 'Hårdplast' },
	{ name: 'Pulka', target: Icons.Hardplast, icon: '🛷', category: 'Hårdplast' },
	{ name: 'Fotboll', target: Icons.SportFritid, icon: '⚽', category: 'Sport & Fritid' },
	{ name: 'Skidor', target: Icons.SportFritid, icon: '🎿', category: 'Sport & Fritid' },
	{ name: 'Tryckimpregnerat', target: Icons.ImpragneratTra, icon: '🪵', category: 'Impregnerat Trä' },
	{ name: 'Trasigt fiskenät', target: Icons.Fiskeredskap, icon: '🎣', category: 'Fiskeredskap' },
	{ name: 'Frityrolja', target: Icons.Matfett, icon: '🛢️', category: 'Matfett' },
	{ name: 'Lastpall', target: Icons.Pallinsamling, icon: '🪚', category: 'Pallinsamling' },
	{ name: 'Användbara kläder', target: Icons.Aterbruk, icon: '👗', category: 'Återbruk' },
	{ name: 'Fina leksaker', target: Icons.Aterbruk, icon: '🧸', category: 'Återbruk' }
];